name: Build Mod
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e # NDK yang cocok dengan template LGL
      - name: Build with ndk-build
        run: ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./jni/Android.mk APP_PLATFORM=android-21
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: libmod
          path: libs/arm64-v8a/libMyLibName.so
