name: Build Mod
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          chmod +x build.sh
          ./build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: libmod
          path: output/*.so
